# Generated by Django 2.2.4 on 2019-10-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signin',
            options={'verbose_name': 'Signins'},
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='Email',
            new_name='email',
        ),
    ]
